### ISSUE TITLE
touch scroll y axis on ios

### ISSUE THREAD

**Issue by dav11d** [estrattonbailey/noodle#2]
Unable to scroll window y axis when touching slideshow with ios/safari. 

Working ok in chrome dev tools, apologies if this is already referenced

**Comment by estrattonbailey** [comment]
@dav11d hello again! Yeah I've noticed this as well in some cases. It's a common problem among drag-interacted libraries. I'd definitely like to implement a fix, but I'm thinking it'll take some real time to test and debug.

Would absolutely love to help if you felt up to giving it a go. Otherwise I should be able to get to it in the next few weeks.

Just for reference, here are a couple (probably) related issues:
https://github.com/metafizzy/flickity/issues/740
https://github.com/Shopify/draggable/issues/198

**Comment by estrattonbailey** [comment]
@dav11d I just published `1.8.0`, which updates `rosin`. I believe the vertical scrolling issue should be resolved!

**Comment by estrattonbailey** [comment]
@dav11d did some more testing and I'm confident this is solved. Let me know if you see otherwise!
