### ISSUE TITLE
Allow config for fading.

### ISSUE THREAD

**Issue by patrickbjohnson** [estrattonbailey/noodle#4]
Flickity had similar issues but adding a small fade option could be nice!

**Comment by estrattonbailey** [comment]
Yo! Yeah, I followed that issue for a while too back in the day. Idk we talked about this in Slack, but sorry for the long delay here.

The truth is turning on fading for a otherwise flickable slideshow is like turning off 90% of the functionality. Creating a fading slideshow is trivial to do on its own, so I don't think it makes sense to include in a library like this. They're kind of the antithesis of each other.
